# Generated by Django 4.2.1 on 2023-05-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0.0, verbose_name='Total')),
                ('shipping', models.FloatField(default=0.0, verbose_name='Frete')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25, verbose_name='Título')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('price', models.FloatField(default=0.0, verbose_name='Preço')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('image_cover', models.FileField(help_text='Por favor, tire a foto na vertical.', upload_to='static/', verbose_name='Imagem de capa')),
                ('image2', models.FileField(help_text='Por favor, tire a foto na vertical.', upload_to='static/', verbose_name='Imagem 2')),
                ('image3', models.FileField(help_text='Por favor, tire a foto na vertical.', upload_to='static', verbose_name='Imagem 3')),
                ('cart', models.ManyToManyField(editable=False, to='app.cart', verbose_name='Carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.SlugField(max_length=900, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('total', models.FloatField(default=0.0, verbose_name='Total')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Telefone')),
                ('phone_number2', models.CharField(max_length=14, verbose_name='Telefone 2')),
                ('state', models.CharField(max_length=25, verbose_name='Estado')),
                ('district', models.CharField(max_length=25, verbose_name='Bairro')),
                ('street', models.CharField(max_length=25, verbose_name='Rua')),
                ('street_number', models.IntegerField(verbose_name='Número da rua')),
                ('complement', models.CharField(max_length=150, null=True, verbose_name='Complemento')),
                ('postal_code', models.CharField(max_length=150, verbose_name='CEP')),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('aceito', 'aceito'), ('despachado', 'despachado')], default='pendente', max_length=25, verbose_name='Status')),
                ('tracking_link', models.URLField(null=True, verbose_name='Link de rastreamento')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart', verbose_name='Carrinho')),
                ('products', models.ManyToManyField(to='app.product', verbose_name='Produtos')),
            ],
        ),
    ]
