# Generated by Django 4.2.1 on 2023-05-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cep',
            new_name='postal_code',
        ),
    ]
