# Generated by Django 4.2.1 on 2023-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Contagem das abóboras', max_length=25, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(default='Não despachado', null=True, verbose_name='Link de rastreamento'),
        ),
    ]
