# Generated by Django 4.2.1 on 2023-05-26 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart', verbose_name='Carrinho'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.SlugField(max_length=900, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(help_text='Por favor, tire a foto na vertical.', upload_to='static/', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(help_text='Por favor, tire a foto na vertical.', upload_to='static', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_cover',
            field=models.FileField(help_text='Por favor, tire a foto na vertical.', upload_to='static/', verbose_name='Imagem de capa'),
        ),
    ]
