# Generated by Django 4.2.1 on 2023-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_apartment_order_floor_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(default='S/N', help_text='Anule, se não tiver', null=True, verbose_name='Número da residência'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(default='S/N', help_text='Anule, se não tiver', max_length=25, verbose_name='Bairro'),
        ),
    ]
